apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: elastic-system
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: quickstart
    namespace: elastic-system
  kibanaRef:
    name: quickstart
    namespace: elastic-system
  http:
    tls:
      selfSignedCertificate:
        disabled: true